const Q = [
  {id:1,t:'Algebra',d:'hard',p:'Agar x + 1/x = 3 bo‘lsa, x² + 1/x² ning qiymatini toping.',o:['5','7','9','11'],a:1,e:'(x+1/x)²=x²+2+1/x². Demak x²+1/x²=9−2=7.'},
  {id:2,t:'Algebra',d:'hard',p:'a+b=7 va ab=10 bo‘lsa, a³+b³ ni toping.',o:['103','113','123','133'],a:3,e:'a³+b³=(a+b)³−3ab(a+b)=343−210=133.'},
  {id:3,t:'Tenglama',d:'hard',p:'x²−6x+1=0 tenglamaning ildizlari r₁ va r₂ bo‘lsa, 1/r₁+1/r₂ nimaga teng?',o:['1','3','6','12'],a:2,e:'1/r₁+1/r₂=(r₁+r₂)/(r₁r₂)=6/1=6.'},
  {id:4,t:'Ko‘rsatkichli tenglama',d:'hard',p:'2ˣ+2⁻ˣ=5/2 bo‘lsa, x ning barcha qiymatlari qaysi?',o:['x=0','x=1','x=−1 yoki 1','x=2 yoki −2'],a:2,e:'y=2ˣ desak y+1/y=5/2. 2y²−5y+2=0, y=2 yoki 1/2; x=1 yoki −1.'},
  {id:5,t:'Progressiya',d:'hard',p:'Σ[k=1 dan n gacha] 1/(k(k+1))=9/10 bo‘lsa, n ni toping.',o:['8','9','10','11'],a:1,e:'Yig‘indi teleskopik: 1−1/(n+1)=9/10. Bundan n+1=10, n=9.'},
  {id:6,t:'Kombinatorika',d:'hard',p:'10 kishidan 2 kishilik juftliklar sonidan 10 kishilik bir kishilik tanlovlar soni ayrilsa, natija nechaga teng?',o:['25','30','35','40'],a:2,e:'C(10,2)−C(10,1)=45−10=35.'},
  {id:7,t:'Algebra',d:'hard',p:'x va y musbat, x²+y²=25, xy=12. x+y ni toping.',o:['5','6','7','8'],a:2,e:'(x+y)²=x²+y²+2xy=25+24=49. Musbatligi sabab x+y=7.'},
  {id:8,t:'Trigonometriya',d:'hard',p:'sin t+cos t ifodaning eng katta qiymatini toping.',o:['1','√2','2','√3'],a:1,e:'sin t+cos t=√2·sin(t+45°), maksimal qiymat √2.'},
  {id:9,t:'Geometriya',d:'hard',p:'Tomonlari 13, 14, 15 bo‘lgan uchburchak yuzini toping.',o:['72','78','84','90'],a:2,e:'Geron formulasi: p=21, S=√(21·8·7·6)=84.'},
  {id:10,t:'Geometriya',d:'hard',p:'Radiusi 13 bo‘lgan doirada markazdan 5 masofadagi vatar uzunligi nechaga teng?',o:['10','12','24','26'],a:2,e:'Yarim vatar √(13²−5²)=12. Vatar 24.'},
  {id:11,t:'Geometriya',d:'hard',p:'Aylana ichidagi markaziy burchak 140° bo‘lsa, shu yoyga tiralgan ichki burchak nechaga teng?',o:['35°','70°','140°','280°'],a:1,e:'Ichki burchak shu yoyning yarmiga teng: 140°/2=70°.'},
  {id:12,t:'Koordinatalar',d:'hard',p:'A(1,2) va B(5,5) kesmaning o‘rta nuqtasi koordinatalarini toping.',o:['(2,3)','(3,3.5)','(3,4)','(4,3.5)'],a:1,e:'M((1+5)/2,(2+5)/2)=(3,3.5).'},
  {id:13,t:'Logarifm',d:'hard',p:'log₂x+log₂(x−2)=3 tenglamani yeching.',o:['x=2','x=3','x=4','x=6'],a:2,e:'x>2. log₂[x(x−2)]=3, x²−2x=8. Musbat yechim x=4.'},
  {id:14,t:'Algebra',d:'hard',p:'x²−1 ga bo‘lganda x²⁰²⁶ ning qoldig‘i nima bo‘ladi?',o:['−1','0','1','x'],a:2,e:'x²≡1 (mod x²−1). Daraja juft, shuning uchun qoldiq 1.'},
  {id:15,t:'Sonlar nazariyasi',d:'hard',p:'EKUB(2¹⁰⁰−1, 2⁶⁰−1) ni toping.',o:['2¹⁰−1','2²⁰−1','2³⁰−1','2⁴⁰−1'],a:1,e:'EKUB(aᵐ−1,aⁿ−1)=a^EKUB(m,n)−1. EKUB(100,60)=20.'},
  {id:16,t:'Algebra',d:'hard',p:'x va y musbat butun sonlar, x+y=20. xy ning eng katta qiymati?',o:['90','96','100','110'],a:2,e:'Yig‘indi berilganda ko‘paytma sonlar teng bo‘lganda maksimal: 10·10=100.'},
  {id:17,t:'Progressiya',d:'hard',p:'Geometrik progressiyada b₁=2, q=3. Dastlabki 5 had yig‘indisini toping.',o:['120','180','242','363'],a:2,e:'S₅=2(3⁵−1)/(3−1)=242.'},
  {id:18,t:'Integral',d:'hard',p:'∫₀¹(3x²+2x)dx qiymatini toping.',o:['1','2','3','4'],a:1,e:'Boshlang‘ich funksiya x³+x². 1 dan 0 ayirilsa 2.'},
  {id:19,t:'Hosila',d:'hard',p:'y=x²+1 grafigiga x=2 nuqtada o‘tkazilgan urinmaning burchak koeffitsiyenti?',o:['2','3','4','5'],a:2,e:'y′=2x, y′(2)=4.'},
  {id:20,t:'Modul',d:'hard',p:'|x−1|+|x+1|=6 tenglamaning ildizlari yig‘indisini toping.',o:['−6','0','2','6'],a:1,e:'Yechimlar x=−3 va x=3. Ularning yig‘indisi 0.'},
  {id:21,t:'Kasrli tenglama',d:'hard',p:'(x−1)/(x+1)=2 tenglamani yeching.',o:['−3','−1','1','3'],a:0,e:'x−1=2x+2, demak x=−3; x≠−1 shart bajariladi.'},
  {id:22,t:'Kvadrat tenglama',d:'hard',p:'x²−2ax+a²−1=0 tenglama ildizlari farqi nechaga teng?',o:['1','2','a','2a'],a:1,e:'Ildizlar a−1 va a+1, farqi 2.'},
  {id:23,t:'Ehtimollik',d:'hard',p:'Ikki kubik tashlanganda yig‘indi 9 bo‘lish ehtimoli?',o:['1/12','1/9','1/6','1/4'],a:1,e:'(3,6),(4,5),(5,4),(6,3) — 4 holat. 4/36=1/9.'},
  {id:24,t:'Kombinatorika',d:'hard',p:'5 erkak va 4 ayoldan kamida 1 ayol qatnashadigan 3 kishilik guruhlar soni?',o:['64','70','74','80'],a:2,e:'Jami C(9,3)=84. Faqat erkaklar C(5,3)=10. 84−10=74.'},
  {id:25,t:'Funksiya',d:'hard',p:'f(x)=x/(x+1) bo‘lsa, f(f(x)) nimaga teng?',o:['x/(x+1)','x/(2x+1)','(x+1)/(2x+1)','1/(x+1)'],a:1,e:'f(f(x))=[x/(x+1)]/[x/(x+1)+1]=x/(2x+1).'},
  {id:26,t:'Algebra',d:'hard',p:'a,b,c haqiqiy sonlar uchun a²+b²+c²=ab+bc+ca. Qaysi xulosa to‘g‘ri?',o:['a,b,c juft-juft teng','a+b+c=0','abc=1','Faqat a=b'],a:0,e:'(a−b)²+(b−c)²+(c−a)²=0. Demak a=b=c.'},
  {id:27,t:'Geometriya',d:'hard',p:'Muntazam ko‘pburchakning ichki burchagi 150° bo‘lsa, tomonlar soni nechta?',o:['8','10','12','15'],a:2,e:'180−360/n=150. 360/n=30, n=12.'},
  {id:28,t:'Geometriya',d:'hard',p:'Teng yonli uchburchakning yon tomonlari 13, asosi 10. Uning balandligi?',o:['5','10','12','13'],a:2,e:'Balandlik asosni 5 va 5 ga bo‘ladi: h=√(13²−5²)=12.'},
  {id:29,t:'Stereometriya',d:'hard',p:'Radiusi 3 bo‘lgan sharning hajmini toping.',o:['9π','18π','27π','36π'],a:3,e:'V=4πr³/3=4π·27/3=36π.'},
  {id:30,t:'Stereometriya',d:'hard',p:'Kubning fazoviy diagonali 6√3 bo‘lsa, qirrasi nechaga teng?',o:['2','3','6','18'],a:2,e:'d=a√3. Demak a=6.'},
  {id:31,t:'Ko‘phad',d:'hard',p:'x³−3x+1 ko‘phadning ildizlari r₁,r₂,r₃ bo‘lsa, r₁r₂+r₁r₃+r₂r₃ nimaga teng?',o:['−3','−1','1','3'],a:0,e:'Viyet bo‘yicha x³+0x²−3x+1 da juft ko‘paytmalar yig‘indisi −3.'},
  {id:32,t:'Logarifm',d:'hard',p:'log₃(x−1)+log₃(x+1)=2 tenglamaning yechimi?',o:['√10','√11','√12','4'],a:0,e:'x>1 va (x−1)(x+1)=9. x²=10, x=√10. Variantlar ichida to‘g‘ri javob √10.'},
  {id:33,t:'Tenglama',d:'hard',p:'x⁴−5x²+4=0 tenglamaning musbat ildizlari yig‘indisi?',o:['2','3','4','5'],a:1,e:'(x²−1)(x²−4)=0. Musbat ildizlar 1 va 2, yig‘indi 3.'},
  {id:34,t:'Irratsional tenglama',d:'hard',p:'√(x+3)−√(x−1)=2 tenglamaning yechimi?',o:['1','2','3','4'],a:0,e:'Domen x≥1. A−B=2 va A²−B²=4 bo‘lgani uchun A+B=2; bundan B=0 va x=1.'},
  {id:35,t:'Ko‘rsatkichli tenglama',d:'hard',p:'3ˣ+3²⁻ˣ=10 tenglamaning barcha ildizlari?',o:['x=0','x=2','x=0 yoki 2','x=1'],a:2,e:'y=3ˣ: y+9/y=10, y²−10y+9=0. y=1 yoki 9, x=0 yoki 2.'},
  {id:36,t:'Algebra',d:'hard',p:'a+b+c=6 va ab+bc+ca=11 bo‘lsa, a²+b²+c² ni toping.',o:['14','22','25','36'],a:0,e:'(a+b+c)²=a²+b²+c²+2(ab+bc+ca). 36−22=14.'},
  {id:37,t:'Trigonometriya',d:'hard',p:'tan t=1/2 bo‘lsa, cos 2t qiymatini toping.',o:['1/5','2/5','3/5','4/5'],a:2,e:'cos2t=(1−tan²t)/(1+tan²t)=(1−1/4)/(1+1/4)=3/5.'},
  {id:38,t:'Sonlar nazariyasi',d:'hard',p:'n²+n+1 soni n+1 ga bo‘linganda qoldiq nima bo‘ladi?',o:['0','1','n','n−1'],a:1,e:'n≡−1 (mod n+1). n²+n+1≡1−1+1=1.'},
  {id:39,t:'Tengsizlik',d:'hard',p:'x(1−x) ifodaning eng katta qiymatini toping.',o:['0','1/4','1/2','1'],a:1,e:'x(1−x)=1/4−(x−1/2)². Maksimum 1/4.'},
  {id:40,t:'Rekursiv ketma-ketlik',d:'hard',p:'a₁=1, aₙ₊₁=2aₙ+1 bo‘lsa, a₅ ni toping.',o:['15','21','31','63'],a:2,e:'a₂=3, a₃=7, a₄=15, a₅=31.'},
  {id:41,t:'Algebra',d:'hard',p:'x+y=5 va x³+y³=35 bo‘lsa, x²+y² ni toping.',o:['11','13','15','17'],a:1,e:'x³+y³=(x+y)³−3xy(x+y). 35=125−15xy, xy=6. x²+y²=25−12=13.'},
  {id:42,t:'Binom',d:'hard',p:'(1+x)ⁿ yoyilmasidagi koeffitsiyentlar yig‘indisi 1024 bo‘lsa, n nechaga teng?',o:['5','8','10','12'],a:2,e:'Koeffitsiyentlar yig‘indisi 2ⁿ=1024=2¹⁰, demak n=10.'},
  {id:43,t:'Analitik geometriya',d:'hard',p:'(0,0) nuqtadan 3x−4y+12=0 to‘g‘ri chiziqqacha masofa?',o:['4/5','5/2','12/5','3'],a:2,e:'Masofa |12|/√(3²+(-4)²)=12/5.'},
  {id:44,t:'Geometriya',d:'hard',p:'Uchburchakda ikki tomon 5 va 7, ular orasidagi burchak 60°. Uchinchi tomon uzunligi?',o:['√39','√49','√61','√74'],a:0,e:'Kosinuslar teoremasi: c²=25+49−2·5·7·1/2=39. Demak c=√39. Variantlar ichida to‘g‘ri javob √39.'},
  {id:45,t:'Kombinatorika',d:'hard',p:'1,2,3,4,5 raqamlaridan takrorlamasdan tuzilgan uch xonali sonlardan 3 ga bo‘linadiganlari nechta?',o:['12','18','24','30'],a:2,e:'Raqamlar yig‘indisi 3 ga bo‘linishi kerak. Uchliklar: 1,2,3; 1,3,5; 2,3,4; 3,4,5 — 4 ta, har biri 6 tartibda: 24. Variantlar ichida to‘g‘ri javob 24.'}
];
const P=[['m1','1 oy',1,20000],['m3','3 oy',3,45000],['m6','6 oy',6,80000],['m9','9 oy',9,105000],['m12','12 oy',12,120000]];
// Faqat rasmiy UZBMB/DTM manbalarida aniq topilgan o‘tgan savollar keyin shu bankka kiritiladi. Topilmaganlari ataylab savol sifatida qo‘shilmaydi.
const OFFICIAL_ARCHIVE=[
  {year:2019,status:'Topilmadi',url:'https://uzbmb.uz/',note:'2019-yil uchun rasmiy milliy sertifikat matematika savol kitobchasi topilmadi.'},
  {year:2020,status:'Topilmadi',url:'https://uzbmb.uz/upload/file/pdf/matematika.pdf',note:'Rasmiy namuna bor, ammo o‘tgan imtihon varianti emas; savollar bankiga kiritilmadi.'},
  {year:2021,status:'Topilmadi',url:'https://uzbmb.uz/upload/file/2021_namuna/Matematika.pdf',note:'Rasmiy namuna/model to‘plam bor, ammo e’lon qilingan o‘tgan imtihon savolnomasi emas.'},
  {year:2022,status:'Topilmadi',url:'https://uzbmb.uz/upload/file/pdf/mtt/Matematika.pdf',note:'Rasmiy spetsifikatsiya va namuna bor, ammo o‘tgan imtihon savolnomasi emas.'},
  {year:2023,status:'Topilmadi',url:'https://uzbmb.uz/post/view/matematika-va-biologiya-fanlaridan-milliy-sertifikat-imtihonlari-bo-lib-o-tdi2',note:'Imtihon o‘tkazilgani haqida rasmiy xabar bor, savol kitobchasi e’lon qilinmagan.'},
  {year:2024,status:'Topilmadi',url:'https://uzbmb.uz/post/view/milliy-sertifikat-imtihoni-natijalari-1',note:'Rasmiy natija/xabar bor, savol kitobchasi e’lon qilinmagan.'},
  {year:2025,status:'Topilmadi',url:'https://uzbmb.uz/upload/file/post/statistics/pdf/saytga_ms_mat_rash-5.10.2025.pdf',note:'Rasmiy statistika bor, savol kitobchasi e’lon qilinmagan.'}
];
const ADMIN_USERNAME='iakubov3503', REQUIRED_CHANNEL='@solobuilderhq', TTL=86400000*45, EXAM_MS=150*60*1000, MEM=new Map();
const api=(env,method,body)=>fetch('https://api.telegram.org/bot'+env.TELEGRAM_BOT_TOKEN+'/'+method,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}).then(r=>r.json());
const K=rows=>({inline_keyboard:rows}), E=x=>String(x??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const cash=n=>Number(n).toLocaleString('uz-UZ')+' so\'m', plan=id=>P.find(x=>x[0]===id);
const dayKey=()=>new Date(Date.now()+5*3600000).toISOString().slice(0,10), yesterday=()=>new Date(Date.now()+5*3600000-86400000).toISOString().slice(0,10);
async function read(env,key){if(env.DATA){try{return await env.DATA.get(key,'json')}catch{}}let x=MEM.get(key);return x&&Date.now()-x.u<TTL?x.v:null}
async function write(env,key,val){if(env.DATA){try{await env.DATA.put(key,JSON.stringify(val));return}catch{}}MEM.set(key,{u:Date.now(),v:val})}
async function drop(env,key){if(env.DATA){try{await env.DATA.delete(key);return}catch{}}MEM.delete(key)}
const ukey=id=>'user:'+id, skey=id=>'session:'+id, subkey=id=>'sub:'+id;
async function getUser(env,id,meta={}){let u=await read(env,ukey(id));if(!u)u={id:String(id),username:meta.username||'',name:meta.name||'',xp:0,streak:0,lastDay:'',solved:0,correct:0,wrong:0,mistakes:[],badges:[],updated:Date.now()};u.username=meta.username||u.username;u.name=meta.name||u.name;u.updated=Date.now();await write(env,ukey(id),u);return u}
async function adminId(env){let x=await read(env,'admin');return String(x?.id||'')}
async function channelMember(env,id){let r=await api(env,'getChatMember',{chat_id:REQUIRED_CHANNEL,user_id:id});let s=r?.result?.status;return {ok:!!r?.ok,member:['creator','administrator','member','restricted'].includes(s)}}
async function requireChannel(env,id){let cached=await read(env,'channel-ok:'+id);if(cached?.ok)return true;let state=await channelMember(env,id);if(state.member){await write(env,'channel-ok:'+id,{ok:true,at:Date.now()});return true}return false}
async function channelGate(env,id){return api(env,'sendMessage',{chat_id:id,text:'Botdan foydalanish uchun avval @solobuilderhq kanaliga obuna bo‘ling. Keyin “A’zolikni tekshirish” tugmasini bosing.',reply_markup:K([[{text:'Kanalga qo‘shilish',url:'https://t.me/solobuilderhq'}],[{text:'A’zolikni tekshirish',callback_data:'check_channel'}]])})}
async function rememberAdmin(env,m){if(String(m.from?.username||'').toLowerCase()===ADMIN_USERNAME)await write(env,'admin',{id:String(m.chat.id),username:ADMIN_USERNAME})}
async function userText(env,id){let u=await getUser(env,id);return u.name||u.username||String(id)}
function grade(qs,answers){const n=qs.length||45,c=answers.filter(Boolean).length;const p=c/n;return p>=43/45?'A+':p>=38/45?'A':p>=34/45?'B+':p>=30/45?'B':p>=25/45?'C+':'C'}
async function officialArchive(env,id){let text='Rasmiy UZBMB/DTM matematika arxivi\n\nFaqat rasmiy manbada aniq topilgan o‘tgan savollar kiritiladi. Hozircha 2019–2025 yillar uchun rasmiy e’lon qilingan o‘tgan savol kitobchalari topilmadi; namuna, spetsifikatsiya va statistika savol sifatida qo‘shilmadi.\n\n'+OFFICIAL_ARCHIVE.map(x=>x.year+' — '+x.status+'\n'+x.note+'\nManba: '+x.url).join('\n\n');return api(env,'sendMessage',{chat_id:id,text,disable_web_page_preview:true,reply_markup:K([[{text:'Bosh menu',callback_data:'menu'}]])})}
async function menu(env,id){return api(env,'sendMessage',{chat_id:id,text:'Novat AI Math\n\nUZBMB matematika tayyorgarligi. 45 savollik, 2 soat 30 daqiqalik mashq imtihoni. Savollar murakkab author-bankdan; rasmiy arxiv alohida ko‘rsatiladi.',reply_markup:K([[{text:'Bepul test',callback_data:'free'}],[{text:'45 savollik imtihon',callback_data:'exam'}],[{text:'Kun challenge',callback_data:'daily'}],[{text:'Profil / XP',callback_data:'profile'}],[{text:'Reyting TOP-10',callback_data:'rank'}],[{text:'Mening xatolarim',callback_data:'mistakes'}],[{text:'Rasmiy savollar arxivi',callback_data:'official'}],[{text:'Obuna tariflari',callback_data:'plans'}]])})}
async function plans(env,id){let rows=P.map(x=>[{text:x[1]+' - '+cash(x[3]),callback_data:'buy:'+x[0]}]);rows.push([{text:'Bosh menu',callback_data:'menu'}]);return api(env,'sendMessage',{chat_id:id,text:'Tarifni tanlang. To\'lov qo\'lda: '+ADMIN_USERNAME+' ga yozasiz, karta orqali to\'laysiz, chekni botga yuborasiz. Admin HA bossa obuna faollashadi, YO\'Q bossa faollashmaydi.',reply_markup:K(rows)})}
async function buy(env,id,pid){let p=plan(pid);if(!p)return plans(env,id);let r='REQ-'+Date.now().toString(36).toUpperCase();await write(env,'pay:'+id,{p,r,created:Date.now()});return api(env,'sendMessage',{chat_id:id,text:p[1]+' - '+cash(p[3])+'\n\n1. @'+ADMIN_USERNAME+' ga yozing.\n2. To\'lov qiling.\n3. Chekni rasm yoki PDF qilib shu botga yuboring.\n4. Admin HA yoki YO\'Q tugmasini bosadi.\n\nSo\'rov: '+r,reply_markup:K([[{text:'Admin bilan yozishish',url:'https://t.me/'+ADMIN_USERNAME}],[{text:'Chek yuborish',callback_data:'receipt'}]])})}
async function status(env,id){let s=await read(env,subkey(id));if(!s||s.until<Date.now())return api(env,'sendMessage',{chat_id:id,text:'Faol obuna yo\'q.',reply_markup:K([[{text:'Tariflar',callback_data:'plans'}]])});return api(env,'sendMessage',{chat_id:id,text:'Faol obuna: '+s.label+'\nTugash: '+new Date(s.until).toLocaleString('uz-UZ')})}
async function hasSub(env,id){let s=await read(env,subkey(id));return !!s&&s.until>Date.now()}
function pickExam(){return Q.map((_,i)=>i)}
function dailyQuestion(){let n=Math.floor(Date.now()/86400000)%Q.length;return Q[n]}
function remainingText(s){if(s.mode!=='exam')return '';let left=Math.max(0,EXAM_MS-(Date.now()-s.started)),m=Math.floor(left/60000),sec=Math.floor((left%60000)/1000);return '\n\nQolgan vaqt: '+String(m).padStart(2,'0')+':'+String(sec).padStart(2,'0')+(left<=300000?' ⚠️':'')}
async function sendQ(env,id,s){let x=Q[s.qids[s.i]];let prefix=s.mode==='exam'?'Imtihon':s.mode==='daily'?'Kun challenge':'Test';return api(env,'sendMessage',{chat_id:id,text:prefix+' · '+(s.i+1)+'/'+s.qids.length+'\nMavzu: '+x.t+'\n\n'+x.p,reply_markup:K(x.o.map((v,i)=>[{text:String.fromCharCode(65+i)+') '+v,callback_data:'ans:'+s.mode+':'+s.i+':'+i}]))})}
async function start(env,id,mode,meta={}){if((mode==='exam'||mode==='test')&&!await hasSub(env,id))return plans(env,id);if(mode==='free'&&await read(env,'free:'+id))return api(env,'sendMessage',{chat_id:id,text:'Bepul testingiz ishlatilgan.',reply_markup:K([[{text:'Tariflar',callback_data:'plans'}]])});let qids=(mode==='exam'||mode==='free')?pickExam():mode==='daily'?[Q.indexOf(dailyQuestion())]:Q.slice(0,45).map((_,i)=>i);let s={mode,qids,i:0,answers:[],started:Date.now(),lastAt:Date.now(),correctStreak:0,meta};await write(env,skey(id),s);if(mode==='free')await write(env,'free:'+id,{usedAt:Date.now()});await api(env,'sendMessage',{chat_id:id,text:mode==='exam'?'45 savollik imtihon boshlandi. Vaqt: 2 soat 30 daqiqa. Har savolda qolgan vaqt ko‘rsatiladi.':mode==='daily'?'Bugungi challenge boshlandi.': 'Test boshlandi.'});return sendQ(env,id,s)}
async function updateProgress(env,id,x,ok,elapsed,mode){let u=await getUser(env,id);let bonus=ok?10:0;if(ok&&elapsed<30000)bonus+=5;u.xp+=bonus;u.solved++;ok?u.correct++:u.wrong++;let d=dayKey();if(ok){if(u.lastDay!==d)u.streak=u.lastDay===yesterday()?u.streak+1:1;u.lastDay=d;if(u.streak>=7&&!u.badges.includes('7 kunlik olov'))u.badges.push('7 kunlik olov')}if(!ok){u.mistakes.unshift({qid:x.id,topic:x.t,text:x.p,at:Date.now()});u.mistakes=u.mistakes.slice(0,100)}if(x.trap&&ok&&!u.badges.includes('Tuzoqbuzar')){let traps=u.mistakes.filter(m=>Q.find(q=>q.id===m.qid)?.trap).length;if(traps>=10)u.badges.push('Tuzoqbuzar')}await write(env,ukey(id),u);return {u,bonus}}
async function answer(env,id,mode,idx,ch){let s=await read(env,skey(id));if(!s||s.mode!==mode)return menu(env,id);if(mode==='exam'&&Date.now()-s.started>=EXAM_MS)return finish(env,id,mode,true);if(+idx!==s.i)return api(env,'sendMessage',{chat_id:id,text:'Bu eski savol tugmasi.'});let x=Q[s.qids[s.i]],ok=+ch===x.a,elapsed=Date.now()-s.lastAt;s.answers[s.i]=ok;s.correctStreak=ok?s.correctStreak+1:0;let pr=await updateProgress(env,id,x,ok,elapsed,mode);s.lastAt=Date.now();await write(env,skey(id),s);return api(env,'sendMessage',{chat_id:id,text:(ok?'To\'g\'ri ✅':'Noto\'g\'ri ❌')+'  '+(pr.bonus?'+ '+pr.bonus+' XP':'')+'\n\nYechim: '+x.e+'\nTo\'g\'ri javob: '+x.o[x.a],reply_markup:K([[{text:s.i+1<s.qids.length?'Keyingi':'Natija',callback_data:s.i+1<s.qids.length?'next:'+mode:'finish:'+mode}]])})}
async function finish(env,id,mode,timedOut=false){let s=await read(env,skey(id));if(!s)return menu(env,id);let qs=s.qids.map(i=>Q[i]),c=s.answers.filter(Boolean).length;await drop(env,skey(id));let u=await getUser(env,id);if(mode==='daily'){u.xp+=50;if(!u.badges.includes('Kun challenge'))u.badges.push('Kun challenge');await write(env,ukey(id),u)}return api(env,'sendMessage',{chat_id:id,text:(mode==='exam'?(timedOut?'Vaqt tugadi — imtihon natijasi':'Imtihon natijasi'):mode==='daily'?'Challenge natijasi':'Test natijasi')+'\n\nTo\'g\'ri: '+c+'/'+qs.length+'\nXato: '+(qs.length-c)+'\nBaho: '+grade(qs,s.answers)+'\n\nProfil: '+u.xp+' XP · streak '+u.streak+' kun',reply_markup:K([[{text:'Profil / XP',callback_data:'profile'}],[{text:'Mening xatolarim',callback_data:'mistakes'}],[{text:'Bosh menu',callback_data:'menu'}]])})}
async function profile(env,id){let u=await getUser(env,id);return api(env,'sendMessage',{chat_id:id,text:'Profil\n\nXP: '+u.xp+'\nStreak: '+u.streak+' kun\nYechilgan: '+u.solved+'\nTo\'g\'ri: '+u.correct+'\nXato: '+u.wrong+'\nNishonlar: '+(u.badges.join(', ')||'Hali yo‘q'),reply_markup:K([[{text:'Reyting',callback_data:'rank'}],[{text:'Bosh menu',callback_data:'menu'}]])})}
async function mistakes(env,id){let u=await getUser(env,id);let a=u.mistakes.slice(0,10);return api(env,'sendMessage',{chat_id:id,text:a.length?'Mening xatolarim\n\n'+a.map((m,i)=>(i+1)+'. '+m.topic+' — '+m.text).join('\n\n'):'Hali xatolar tarixi yo‘q.',reply_markup:K([[{text:'Zaif mavzular',callback_data:'weak'}],[{text:'Bosh menu',callback_data:'menu'}]])})}
async function weak(env,id){let u=await getUser(env,id),c={};for(let m of u.mistakes)c[m.topic]=(c[m.topic]||0)+1;let text=Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>k+': '+v+' ta xato').join('\n');return api(env,'sendMessage',{chat_id:id,text:text?'Zaif mavzular\n\n'+text:'Hali yetarli ma’lumot yo‘q.',reply_markup:K([[{text:'Mening xatolarim',callback_data:'mistakes'}]])})}
async function rank(env,id){let keys=[],cursor;do{let r=env.DATA?await env.DATA.list({prefix:'user:',cursor}):{keys:[]};keys.push(...(r.keys||[]));cursor=r.list_complete?undefined:r.cursor}while(cursor&&keys.length<1000);let rows=[];for(let k of keys){let u=await read(env,k.name);if(u)rows.push(u)}rows.sort((a,b)=>b.xp-a.xp);let text='TOP-10 reyting\n\n'+rows.slice(0,10).map((u,i)=>(i+1)+'. '+E(u.name||u.username||u.id)+' — '+u.xp+' XP').join('\n');return api(env,'sendMessage',{chat_id:id,text,parse_mode:'HTML',reply_markup:K([[{text:'Profil',callback_data:'profile'}],[{text:'Bosh menu',callback_data:'menu'}]])})}
async function receipt(env,m){let p=await read(env,'pay:'+m.chat.id),aid=await adminId(env);if(!p)return api(env,'sendMessage',{chat_id:m.chat.id,text:'Avval /plans dan tarif tanlang.'});if(!aid)return api(env,'sendMessage',{chat_id:m.chat.id,text:'Admin hali /start qilmagan.'});if(!m.photo&&!m.document)return api(env,'sendMessage',{chat_id:m.chat.id,text:'Chekni rasm yoki PDF ko‘rinishida yuboring.'});let f=await api(env,'forwardMessage',{chat_id:aid,from_chat_id:m.chat.id,message_id:m.message_id}),mid=f?.result?.message_id||0;await api(env,'sendMessage',{chat_id:aid,text:'Yangi chek\nSo‘rov: '+p.r+'\nFoydalanuvchi: '+m.chat.id+'\nTarif: '+p.p[1]+'\nSumma: '+cash(p.p[3]),reply_markup:K([[{text:'HA - faollashtirish',callback_data:'yes:'+m.chat.id+':'+p.p[0]+':'+mid},{text:'YO‘Q - rad etish',callback_data:'no:'+m.chat.id}]])});return api(env,'sendMessage',{chat_id:m.chat.id,text:'Chek admin ga yuborildi. Tasdiqlashni kuting.'})}
async function decide(env,c,yes){let aid=await adminId(env),id=String(c.message.chat.id),d=String(c.data).split(':');if(id!==aid)return api(env,'answerCallbackQuery',{callback_query_id:c.id,text:'Faqat admin.',show_alert:true});await api(env,'answerCallbackQuery',{callback_query_id:c.id,text:yes?'Faollashdi':'Rad etildi'});let uid=d[1];if(!yes)return api(env,'sendMessage',{chat_id:uid,text:'Obuna tasdiqlanmadi. Admin bilan bog‘laning: @'+ADMIN_USERNAME});let p=plan(d[2])||P[0],old=await read(env,subkey(uid)),base=old&&old.until>Date.now()?old.until:Date.now(),until=base+p[2]*30*86400000;await write(env,subkey(uid),{plan:p[0],label:p[1],until,approvedAt:Date.now()});return api(env,'sendMessage',{chat_id:uid,text:'Obuna faollashtirildi ✅\nTarif: '+p[1]+'\nTugash: '+new Date(until).toLocaleString('uz-UZ')})}
async function msg(env,m){await rememberAdmin(env,m);let id=m.chat.id,t=String(m.text||'').trim(),meta={username:m.from?.username||'',name:m.from?.first_name||''};await getUser(env,id,meta);let member=await requireChannel(env,id);if(!member)return channelGate(env,id);if(m.photo||m.document)return receipt(env,m);if(t==='/start'||t==='/help')return menu(env,id);if(t==='/plans'||t==='/subscribe')return plans(env,id);if(t==='/status')return status(env,id);if(t==='/free')return start(env,id,'free');if(t==='/exam')return start(env,id,'exam');if(t==='/test'||t==='/quiz')return start(env,id,'test');if(t==='/daily')return start(env,id,'daily');if(t==='/profile')return profile(env,id);if(t==='/rank'||t==='/leaderboard')return rank(env,id);if(t==='/mistakes')return mistakes(env,id);if(t==='/weak')return weak(env,id);if(t==='/official'||t==='/archive')return officialArchive(env,id);if(t==='/cancel'){await drop(env,skey(id));return api(env,'sendMessage',{chat_id:id,text:'Test bekor qilindi.'})}return api(env,'sendMessage',{chat_id:id,text:'Buyruqlar: /free, /exam, /daily, /test, /plans, /status, /profile, /rank, /mistakes, /weak, /official, /cancel'})}
async function cb(env,c){let id=c.message.chat.id,d=String(c.data||'');if(!d.startsWith('yes:')&&!d.startsWith('no:'))await api(env,'answerCallbackQuery',{callback_query_id:c.id});if(d==='check_channel'){if(await requireChannel(env,id))return menu(env,id);return channelGate(env,id)}if(!d.startsWith('yes:')&&!d.startsWith('no:')&&!await requireChannel(env,id))return channelGate(env,id);if(d==='menu')return menu(env,id);if(d==='plans')return plans(env,id);if(d==='free')return start(env,id,'free');if(d==='exam')return start(env,id,'exam');if(d==='daily')return start(env,id,'daily');if(d==='profile')return profile(env,id);if(d==='rank')return rank(env,id);if(d==='mistakes')return mistakes(env,id);if(d==='weak')return weak(env,id);if(d==='official')return officialArchive(env,id);if(d==='status')return status(env,id);if(d.startsWith('buy:'))return buy(env,id,d.slice(4));if(d==='receipt')return api(env,'sendMessage',{chat_id:id,text:'Chekni rasm yoki PDF qilib yuboring.'});if(d.startsWith('next:')){let s=await read(env,skey(id));if(!s)return menu(env,id);s.i++;await write(env,skey(id),s);return sendQ(env,id,s)}if(d.startsWith('finish:'))return finish(env,id,d.split(':')[1]);if(d.startsWith('ans:')){let x=d.split(':');return answer(env,id,x[1],x[2],x[3])}if(d.startsWith('yes:'))return decide(env,c,true);if(d.startsWith('no:'))return decide(env,c,false)}
async function scheduled(env){let now=new Date(Date.now()+5*3600000);if(now.getUTCHours()!==8)return;let key='daily-sent:'+dayKey();if(await read(env,key))return;let q=dailyQuestion(),r=env.DATA?await env.DATA.list({prefix:'user:',limit:1000}):{keys:[]};for(let k of r.keys||[]){let u=await read(env,k.name);if(u?.id)await api(env,'sendMessage',{chat_id:u.id,text:'☀️ Bugungi Kun Challenge\n\n'+q.p,reply_markup:K([[{text:'Boshlash',callback_data:'daily'}]])})}await write(env,key,{sentAt:Date.now()})}
export default {async fetch(request,env,ctx){if(request.method==='GET')return new Response('Novat AI Math - Telegram bot ready');if(request.method!=='POST')return new Response('Method Not Allowed',{status:405});try{let u=await request.json();ctx.waitUntil(u.callback_query?cb(env,u.callback_query):u.message?msg(env,u.message):Promise.resolve())}catch(e){}return new Response('ok')},async scheduled(controller,env,ctx){ctx.waitUntil(scheduled(env))}};
