const Q = [
  {id:1,t:'Algebra',d:'easy',p:'3x+5=20. x=?',o:['3','5','7','25'],a:1,e:'3x=15, demak x=5.'},
  {id:2,t:'Kasrlar',d:'easy',p:'2/3+1/6=?',o:['1/2','5/6','1','2/9'],a:1,e:'2/3=4/6; 4/6+1/6=5/6.'},
  {id:3,t:'Funksiya',d:'medium',p:'f(x)=2x²−3x+1 bo‘lsa f(2)=?',o:['1','3','5','7'],a:1,e:'2·4−6+1=3.'},
  {id:4,t:'Tenglama',d:'medium',p:'x²−5x+6=0 ildizlari?',o:['1,6','2,3','−2,−3','0,6'],a:1,e:'(x−2)(x−3)=0, ildizlar 2 va 3.'},
  {id:5,t:'Geometriya',d:'medium',p:'Katetlar 6 va 8. Gipotenuza?',o:['10','12','14','48'],a:0,e:'Pifagor: c²=36+64=100, c=10.'},
  {id:6,t:'Ehtimollik',d:'medium',p:'3 oq, 2 qora shar bor. Oq shar chiqish ehtimoli?',o:['2/5','3/5','1/2','3/2'],a:1,e:'Jami 5 ta, oq 3 ta: P=3/5.'},
  {id:7,t:'Logarifm',d:'hard',p:'log₂(x−1)=3. x=?',o:['7','8','9','10'],a:2,e:'x−1=8, demak x=9.'},
  {id:8,t:'Tengsizlik',d:'hard',p:'(x−2)(x+3)≤0 yechimi?',o:['x≤−3 yoki x≥2','−3≤x≤2','−2≤x≤3','x<−3'],a:1,e:'Ildizlar −3 va 2; ishora jadvali oralig‘ni beradi.'},
  {id:9,t:'Hosila',d:'hard',p:'y=x³−4x. x=2 dagi hosila?',o:['4','6','8','12'],a:2,e:'y′=3x²−4; y′(2)=12−4=8.'},
  {id:10,t:'Geometriya',d:'hard',p:'r=3 bo‘lgan doira yuzi? π=3.14',o:['9.42','18.84','28.26','37.68'],a:2,e:'S=πr²=3.14·9=28.26.'},
  {id:11,t:'Progressiya',d:'hard',p:'2,5,8,11,... arifmetik progressiyada a₁₀=?',o:['26','29','32','35'],a:1,e:'a₁₀=2+9·3=29.'},
  {id:12,t:'Sistemalar',d:'hard',p:'x+y=7, x−y=1. xy=?',o:['6','10','12','14'],a:2,e:'2x=8, x=4; y=3; xy=12.'},
  {id:13,t:'Algebra',d:'easy',p:'2(x−3)+4=14. x=?',o:['5','7','8','9'],a:1,e:'2x−6+4=14 → 2x=16 → x=8.',trap:true},
  {id:14,t:'Kasrlar',d:'medium',p:'(3/4) : (9/16)=?',o:['1/3','4/3','3/4','9/16'],a:1,e:'Bo‘lishda ikkinchi kasr teskari olinadi: 3/4·16/9=4/3.'},
  {id:15,t:'Geometriya',d:'medium',p:'Uchburchak burchaklari 2x, 3x, 4x. Eng katta burchak?',o:['40°','60°','80°','100°'],a:2,e:'9x=180° → x=20°. Eng kattasi 4x=80°.'},
  {id:16,t:'Trigonometriya',d:'medium',p:'sin30°+cos60°=?',o:['0','1/2','1','√2'],a:2,e:'sin30°=1/2 va cos60°=1/2; yig‘indi 1.'},
  {id:17,t:'Funksiya',d:'medium',p:'y=|x−2| funksiyaning minimum qiymati?',o:['−2','0','2','4'],a:1,e:'Modulning eng kichik qiymati 0, x=2 da.'},
  {id:18,t:'Tenglama',d:'medium',p:'√(x+1)=4. x=?',o:['−17','−15','15','17'],a:2,e:'Ikkala tomon kvadratlanadi: x+1=16 → x=15.'},
  {id:19,t:'Statistika',d:'easy',p:'4, 7, 9, 10 sonlarining o‘rta arifmetigi?',o:['7','7.5','8','8.5'],a:1,e:'(4+7+9+10)/4=30/4=7.5.'},
  {id:20,t:'Ehtimollik',d:'medium',p:'Tanga 2 marta tashlandi. Ikki marta gerb tushish ehtimoli?',o:['1/2','1/3','1/4','3/4'],a:2,e:'4 teng natijadan bittasi GG: 1/4.'},
  {id:21,t:'Stereometriya',d:'hard',p:'Kub qirrasi 3. Uning hajmi?',o:['9','18','27','36'],a:2,e:'V=a³=3³=27.'},
  {id:22,t:'Koordinatalar',d:'medium',p:'A(1,2), B(4,6). AB kesma uzunligi?',o:['3','4','5','7'],a:2,e:'√((4−1)²+(6−2)²)=√25=5.'},
  {id:23,t:'Logarifm',d:'hard',p:'log₃9 + log₃27 =?',o:['3','4','5','6'],a:2,e:'2+3=5.'},
  {id:24,t:'Tengsizlik',d:'medium',p:'|x−1|<2 yechimi?',o:['x<−1','−1<x<3','−2<x<2','x>3'],a:1,e:'−2<x−1<2 → −1<x<3.',trap:true},
  {id:25,t:'Algebra',d:'easy',p:'a=2, b=−3 bo‘lsa a²−2ab+b²=?',o:['1','5','13','25'],a:2,e:'Bu (a−b)²=(2−(−3))²=25.'},
  {id:26,t:'Geometriya',d:'medium',p:'To‘g‘ri to‘rtburchak tomonlari 5 va 8. Perimetri?',o:['13','26','40','80'],a:1,e:'P=2(5+8)=26.'},
  {id:27,t:'Hosila',d:'hard',p:'f(x)=5x²−2x+1. f′(1)=?',o:['3','5','8','10'],a:2,e:'f′=10x−2; f′(1)=8.'},
  {id:28,t:'Progressiya',d:'medium',p:'Geometrik progressiya: b₁=3, q=2. b₅=?',o:['24','32','48','96'],a:2,e:'b₅=3·2⁴=48.'},
  {id:29,t:'Mantiq',d:'easy',p:'Ketma-ketlik: 1, 4, 9, 16, ... keyingi son?',o:['20','24','25','36'],a:2,e:'Kvadratlar ketma-ketligi: 1²,2²,3²,4²,5²=25.'},
  {id:30,t:'Trigonometria',d:'medium',p:'cos²x+sin²x har qanday x uchun nimaga teng?',o:['0','1/2','1','2'],a:2,e:'Asosiy trigonometrik ayniyat: 1.'},
  {id:31,t:'Sistemalar',d:'medium',p:'x+y=10, xy=21. x va y yig‘indisi?',o:['5','10','21','31'],a:1,e:'Yig‘indi shartning o‘zida berilgan: 10.'},
  {id:32,t:'Statistika',d:'medium',p:'2, 3, 3, 5, 8 qatorining medianasi?',o:['2','3','4','5'],a:1,e:'Tartiblangan 5 ta qiymatning o‘rtadagi qiymati 3.'},
  {id:33,t:'Irratsional tenglama',d:'hard',p:'√(x−2)=x−4 tenglamaning yechimi?',o:['2','4','6','Hech biri'],a:2,e:'x≥4. Kvadratlasak x−2=(x−4)²; tekshiruvdan x=6 qoladi.',trap:true},
  {id:34,t:'Bo‘linish',d:'medium',p:'(x²−9)/(x−3) ifoda x=3 da aniqlanganmi?',o:['Ha, qiymati 6','Yo‘q, maxraj 0','Ha, qiymati 0','Faqat x<3'],a:1,e:'x=3 da maxraj 0 bo‘ladi; qisqartirish domen cheklovini yo‘qotmaydi.',trap:true},
  {id:35,t:'Geometriya',d:'hard',p:'Radiusi 4 bo‘lgan shar sirtining yuzi? π=3.14',o:['50.24','100.48','150.72','200.96'],a:2,e:'S=4πr²=4·3.14·16=200.96.'}
];
const P=[['m1','1 oy',1,20000],['m3','3 oy',3,45000],['m6','6 oy',6,80000],['m9','9 oy',9,105000],['m12','12 oy',12,120000]];
const ADMIN_USERNAME='iakubov3503', TTL=86400000*45, MEM=new Map();
const api=(env,method,body)=>fetch('https://api.telegram.org/bot'+env.TELEGRAM_BOT_TOKEN+'/'+method,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}).then(r=>r.json());
const K=rows=>({inline_keyboard:rows}), E=x=>String(x??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const cash=n=>Number(n).toLocaleString('uz-UZ')+' so\'m', plan=id=>P.find(x=>x[0]===id);
const dayKey=()=>new Date(Date.now()+5*3600000).toISOString().slice(0,10), yesterday=()=>new Date(Date.now()+5*3600000-86400000).toISOString().slice(0,10);
async function read(env,key){if(env.DATA){try{return await env.DATA.get(key,'json')}catch{}}let x=MEM.get(key);return x&&Date.now()-x.u<TTL?x.v:null}
async function write(env,key,val){if(env.DATA){try{await env.DATA.put(key,JSON.stringify(val));return}catch{}}MEM.set(key,{u:Date.now(),v:val})}
async function drop(env,key){if(env.DATA){try{await env.DATA.delete(key);return}catch{}}MEM.delete(key)}
const ukey=id=>'user:'+id, skey=id=>'session:'+id, subkey=id=>'sub:'+id;
async function getUser(env,id,meta={}){let u=await read(env,ukey(id));if(!u)u={id:String(id),username:meta.username||'',name:meta.name||'',xp:0,streak:0,lastDay:'',solved:0,correct:0,wrong:0,mistakes:[],badges:[],updated:Date.now()};u.username=meta.username||u.username;u.name=meta.name||u.name;u.updated=Date.now();await write(env,ukey(id),u);return u}
async function adminId(env){let x=await read(env,'admin');return String(x?.id||'')}
async function rememberAdmin(env,m){if(String(m.from?.username||'').toLowerCase()===ADMIN_USERNAME)await write(env,'admin',{id:String(m.chat.id),username:ADMIN_USERNAME})}
async function userText(env,id){let u=await getUser(env,id);return u.name||u.username||String(id)}
function grade(qs,answers){let max=0,got=0;for(let i=0;i<qs.length;i++){let w=qs[i].d==='hard'?1.5:qs[i].d==='medium'?1.25:1;max+=w;if(answers[i])got+=w}let z=max?got/max:0;return z>=.92?'A+':z>=.82?'A':z>=.70?'B+':z>=.58?'B':'C'}
async function menu(env,id){return api(env,'sendMessage',{chat_id:id,text:'Novat AI Math\n\nUZBMB matematika tayyorgarligi. Bepul test, 35 savollik imtihon, XP, streak, reyting va xatolar tarixi.',reply_markup:K([[{text:'Bepul test',callback_data:'free'}],[{text:'35 savollik imtihon',callback_data:'exam'}],[{text:'Kun challenge',callback_data:'daily'}],[{text:'Profil / XP',callback_data:'profile'}],[{text:'Reyting TOP-10',callback_data:'rank'}],[{text:'Mening xatolarim',callback_data:'mistakes'}],[{text:'Obuna tariflari',callback_data:'plans'}]])})}
async function plans(env,id){let rows=P.map(x=>[{text:x[1]+' - '+cash(x[3]),callback_data:'buy:'+x[0]}]);rows.push([{text:'Bosh menu',callback_data:'menu'}]);return api(env,'sendMessage',{chat_id:id,text:'Tarifni tanlang. To\'lov qo\'lda: '+ADMIN_USERNAME+' ga yozasiz, karta orqali to\'laysiz, chekni botga yuborasiz. Admin HA bossa obuna faollashadi, YO\'Q bossa faollashmaydi.',reply_markup:K(rows)})}
async function buy(env,id,pid){let p=plan(pid);if(!p)return plans(env,id);let r='REQ-'+Date.now().toString(36).toUpperCase();await write(env,'pay:'+id,{p,r,created:Date.now()});return api(env,'sendMessage',{chat_id:id,text:p[1]+' - '+cash(p[3])+'\n\n1. @'+ADMIN_USERNAME+' ga yozing.\n2. To\'lov qiling.\n3. Chekni rasm yoki PDF qilib shu botga yuboring.\n4. Admin HA yoki YO\'Q tugmasini bosadi.\n\nSo\'rov: '+r,reply_markup:K([[{text:'Admin bilan yozishish',url:'https://t.me/'+ADMIN_USERNAME}],[{text:'Chek yuborish',callback_data:'receipt'}]])})}
async function status(env,id){let s=await read(env,subkey(id));if(!s||s.until<Date.now())return api(env,'sendMessage',{chat_id:id,text:'Faol obuna yo\'q.',reply_markup:K([[{text:'Tariflar',callback_data:'plans'}]])});return api(env,'sendMessage',{chat_id:id,text:'Faol obuna: '+s.label+'\nTugash: '+new Date(s.until).toLocaleString('uz-UZ')})}
async function hasSub(env,id){let s=await read(env,subkey(id));return !!s&&s.until>Date.now()}
function pickExam(){return Q.map((_,i)=>i)}
function dailyQuestion(){let n=Math.floor(Date.now()/86400000)%Q.length;return Q[n]}
async function sendQ(env,id,s){let x=Q[s.qids[s.i]];let prefix=s.mode==='exam'?'Imtihon':s.mode==='daily'?'Kun challenge':'Test';return api(env,'sendMessage',{chat_id:id,text:prefix+' · '+(s.i+1)+'/'+s.qids.length+'\nMavzu: '+x.t+'\n\n'+x.p,reply_markup:K(x.o.map((v,i)=>[{text:String.fromCharCode(65+i)+') '+v,callback_data:'ans:'+s.mode+':'+s.i+':'+i}]))})}
async function start(env,id,mode,meta={}){if((mode==='exam'||mode==='test')&&!await hasSub(env,id))return plans(env,id);if(mode==='free'&&await read(env,'free:'+id))return api(env,'sendMessage',{chat_id:id,text:'Bepul testingiz ishlatilgan.',reply_markup:K([[{text:'Tariflar',callback_data:'plans'}]])});let qids=mode==='exam'?pickExam():mode==='daily'?[Q.indexOf(dailyQuestion())]:Q.slice(0,12).map((_,i)=>i);let s={mode,qids,i:0,answers:[],started:Date.now(),lastAt:Date.now(),correctStreak:0,meta};await write(env,skey(id),s);if(mode==='free')await write(env,'free:'+id,{usedAt:Date.now()});await api(env,'sendMessage',{chat_id:id,text:mode==='exam'?'35 savollik imtihon boshlandi. Har savol uchun vaqtni kuzating.':mode==='daily'?'Bugungi challenge boshlandi.': 'Test boshlandi.'});return sendQ(env,id,s)}
async function updateProgress(env,id,x,ok,elapsed,mode){let u=await getUser(env,id);let bonus=ok?10:0;if(ok&&elapsed<30000)bonus+=5;u.xp+=bonus;u.solved++;ok?u.correct++:u.wrong++;let d=dayKey();if(ok){if(u.lastDay!==d)u.streak=u.lastDay===yesterday()?u.streak+1:1;u.lastDay=d;if(u.streak>=7&&!u.badges.includes('7 kunlik olov'))u.badges.push('7 kunlik olov')}if(!ok){u.mistakes.unshift({qid:x.id,topic:x.t,text:x.p,at:Date.now()});u.mistakes=u.mistakes.slice(0,100)}if(x.trap&&ok&&!u.badges.includes('Tuzoqbuzar')){let traps=u.mistakes.filter(m=>Q.find(q=>q.id===m.qid)?.trap).length;if(traps>=10)u.badges.push('Tuzoqbuzar')}await write(env,ukey(id),u);return {u,bonus}}
async function answer(env,id,mode,idx,ch){let s=await read(env,skey(id));if(!s||s.mode!==mode)return menu(env,id);if(+idx!==s.i)return api(env,'sendMessage',{chat_id:id,text:'Bu eski savol tugmasi.'});let x=Q[s.qids[s.i]],ok=+ch===x.a,elapsed=Date.now()-s.lastAt;s.answers[s.i]=ok;s.correctStreak=ok?s.correctStreak+1:0;let pr=await updateProgress(env,id,x,ok,elapsed,mode);s.lastAt=Date.now();await write(env,skey(id),s);return api(env,'sendMessage',{chat_id:id,text:(ok?'To\'g\'ri ✅':'Noto\'g\'ri ❌')+'  '+(pr.bonus?'+ '+pr.bonus+' XP':'')+'\n\nYechim: '+x.e+'\nTo\'g\'ri javob: '+x.o[x.a],reply_markup:K([[{text:s.i+1<s.qids.length?'Keyingi':'Natija',callback_data:s.i+1<s.qids.length?'next:'+mode:'finish:'+mode}]])})}
async function finish(env,id,mode){let s=await read(env,skey(id));if(!s)return menu(env,id);let qs=s.qids.map(i=>Q[i]),c=s.answers.filter(Boolean).length;await drop(env,skey(id));let u=await getUser(env,id);if(mode==='daily'){u.xp+=50;if(!u.badges.includes('Kun challenge'))u.badges.push('Kun challenge');await write(env,ukey(id),u)}return api(env,'sendMessage',{chat_id:id,text:(mode==='exam'?'Imtihon natijasi':mode==='daily'?'Challenge natijasi':'Test natijasi')+'\n\nTo\'g\'ri: '+c+'/'+qs.length+'\nXato: '+(qs.length-c)+'\nBaho: '+grade(qs,s.answers)+'\n\nProfil: '+u.xp+' XP · streak '+u.streak+' kun',reply_markup:K([[{text:'Profil / XP',callback_data:'profile'}],[{text:'Mening xatolarim',callback_data:'mistakes'}],[{text:'Bosh menu',callback_data:'menu'}]])})}
async function profile(env,id){let u=await getUser(env,id);return api(env,'sendMessage',{chat_id:id,text:'Profil\n\nXP: '+u.xp+'\nStreak: '+u.streak+' kun\nYechilgan: '+u.solved+'\nTo\'g\'ri: '+u.correct+'\nXato: '+u.wrong+'\nNishonlar: '+(u.badges.join(', ')||'Hali yo‘q'),reply_markup:K([[{text:'Reyting',callback_data:'rank'}],[{text:'Bosh menu',callback_data:'menu'}]])})}
async function mistakes(env,id){let u=await getUser(env,id);let a=u.mistakes.slice(0,10);return api(env,'sendMessage',{chat_id:id,text:a.length?'Mening xatolarim\n\n'+a.map((m,i)=>(i+1)+'. '+m.topic+' — '+m.text).join('\n\n'):'Hali xatolar tarixi yo‘q.',reply_markup:K([[{text:'Zaif mavzular',callback_data:'weak'}],[{text:'Bosh menu',callback_data:'menu'}]])})}
async function weak(env,id){let u=await getUser(env,id),c={};for(let m of u.mistakes)c[m.topic]=(c[m.topic]||0)+1;let text=Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>k+': '+v+' ta xato').join('\n');return api(env,'sendMessage',{chat_id:id,text:text?'Zaif mavzular\n\n'+text:'Hali yetarli ma’lumot yo‘q.',reply_markup:K([[{text:'Mening xatolarim',callback_data:'mistakes'}]])})}
async function rank(env,id){let keys=[],cursor;do{let r=env.DATA?await env.DATA.list({prefix:'user:',cursor}):{keys:[]};keys.push(...(r.keys||[]));cursor=r.list_complete?undefined:r.cursor}while(cursor&&keys.length<1000);let rows=[];for(let k of keys){let u=await read(env,k.name);if(u)rows.push(u)}rows.sort((a,b)=>b.xp-a.xp);let text='TOP-10 reyting\n\n'+rows.slice(0,10).map((u,i)=>(i+1)+'. '+E(u.name||u.username||u.id)+' — '+u.xp+' XP').join('\n');return api(env,'sendMessage',{chat_id:id,text,parse_mode:'HTML',reply_markup:K([[{text:'Profil',callback_data:'profile'}],[{text:'Bosh menu',callback_data:'menu'}]])})}
async function receipt(env,m){let p=await read(env,'pay:'+m.chat.id),aid=await adminId(env);if(!p)return api(env,'sendMessage',{chat_id:m.chat.id,text:'Avval /plans dan tarif tanlang.'});if(!aid)return api(env,'sendMessage',{chat_id:m.chat.id,text:'Admin hali /start qilmagan.'});if(!m.photo&&!m.document)return api(env,'sendMessage',{chat_id:m.chat.id,text:'Chekni rasm yoki PDF ko‘rinishida yuboring.'});let f=await api(env,'forwardMessage',{chat_id:aid,from_chat_id:m.chat.id,message_id:m.message_id}),mid=f?.result?.message_id||0;await api(env,'sendMessage',{chat_id:aid,text:'Yangi chek\nSo‘rov: '+p.r+'\nFoydalanuvchi: '+m.chat.id+'\nTarif: '+p.p[1]+'\nSumma: '+cash(p.p[3]),reply_markup:K([[{text:'HA - faollashtirish',callback_data:'yes:'+m.chat.id+':'+p.p[0]+':'+mid},{text:'YO‘Q - rad etish',callback_data:'no:'+m.chat.id}]])});return api(env,'sendMessage',{chat_id:m.chat.id,text:'Chek admin ga yuborildi. Tasdiqlashni kuting.'})}
async function decide(env,c,yes){let aid=await adminId(env),id=String(c.message.chat.id),d=String(c.data).split(':');if(id!==aid)return api(env,'answerCallbackQuery',{callback_query_id:c.id,text:'Faqat admin.',show_alert:true});await api(env,'answerCallbackQuery',{callback_query_id:c.id,text:yes?'Faollashdi':'Rad etildi'});let uid=d[1];if(!yes)return api(env,'sendMessage',{chat_id:uid,text:'Obuna tasdiqlanmadi. Admin bilan bog‘laning: @'+ADMIN_USERNAME});let p=plan(d[2])||P[0],old=await read(env,subkey(uid)),base=old&&old.until>Date.now()?old.until:Date.now(),until=base+p[2]*30*86400000;await write(env,subkey(uid),{plan:p[0],label:p[1],until,approvedAt:Date.now()});return api(env,'sendMessage',{chat_id:uid,text:'Obuna faollashtirildi ✅\nTarif: '+p[1]+'\nTugash: '+new Date(until).toLocaleString('uz-UZ')})}
async function msg(env,m){await rememberAdmin(env,m);let id=m.chat.id,t=String(m.text||'').trim(),meta={username:m.from?.username||'',name:m.from?.first_name||''};await getUser(env,id,meta);if(m.photo||m.document)return receipt(env,m);if(t==='/start'||t==='/help')return menu(env,id);if(t==='/plans'||t==='/subscribe')return plans(env,id);if(t==='/status')return status(env,id);if(t==='/free')return start(env,id,'free');if(t==='/exam')return start(env,id,'exam');if(t==='/test'||t==='/quiz')return start(env,id,'test');if(t==='/daily')return start(env,id,'daily');if(t==='/profile')return profile(env,id);if(t==='/rank'||t==='/leaderboard')return rank(env,id);if(t==='/mistakes')return mistakes(env,id);if(t==='/weak')return weak(env,id);if(t==='/cancel'){await drop(env,skey(id));return api(env,'sendMessage',{chat_id:id,text:'Test bekor qilindi.'})}return api(env,'sendMessage',{chat_id:id,text:'Buyruqlar: /free, /exam, /daily, /test, /plans, /status, /profile, /rank, /mistakes, /weak, /cancel'})}
async function cb(env,c){let id=c.message.chat.id,d=String(c.data||'');if(!d.startsWith('yes:')&&!d.startsWith('no:'))await api(env,'answerCallbackQuery',{callback_query_id:c.id});if(d==='menu')return menu(env,id);if(d==='plans')return plans(env,id);if(d==='free')return start(env,id,'free');if(d==='exam')return start(env,id,'exam');if(d==='daily')return start(env,id,'daily');if(d==='profile')return profile(env,id);if(d==='rank')return rank(env,id);if(d==='mistakes')return mistakes(env,id);if(d==='weak')return weak(env,id);if(d==='status')return status(env,id);if(d.startsWith('buy:'))return buy(env,id,d.slice(4));if(d==='receipt')return api(env,'sendMessage',{chat_id:id,text:'Chekni rasm yoki PDF qilib yuboring.'});if(d.startsWith('next:')){let s=await read(env,skey(id));if(!s)return menu(env,id);s.i++;await write(env,skey(id),s);return sendQ(env,id,s)}if(d.startsWith('finish:'))return finish(env,id,d.split(':')[1]);if(d.startsWith('ans:')){let x=d.split(':');return answer(env,id,x[1],x[2],x[3])}if(d.startsWith('yes:'))return decide(env,c,true);if(d.startsWith('no:'))return decide(env,c,false)}
async function scheduled(env){let now=new Date(Date.now()+5*3600000);if(now.getUTCHours()!==8)return;let key='daily-sent:'+dayKey();if(await read(env,key))return;let q=dailyQuestion(),r=env.DATA?await env.DATA.list({prefix:'user:',limit:1000}):{keys:[]};for(let k of r.keys||[]){let u=await read(env,k.name);if(u?.id)await api(env,'sendMessage',{chat_id:u.id,text:'☀️ Bugungi Kun Challenge\n\n'+q.p,reply_markup:K([[{text:'Boshlash',callback_data:'daily'}]])})}await write(env,key,{sentAt:Date.now()})}
export default {async fetch(request,env,ctx){if(request.method==='GET')return new Response('Novat AI Math - Telegram bot ready');if(request.method!=='POST')return new Response('Method Not Allowed',{status:405});try{let u=await request.json();ctx.waitUntil(u.callback_query?cb(env,u.callback_query):u.message?msg(env,u.message):Promise.resolve())}catch(e){}return new Response('ok')},async scheduled(controller,env,ctx){ctx.waitUntil(scheduled(env))}};
